apiVersion: v1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  labels:
    app: Ingress
    environment: demo
    authorship: sunil
spec:
  rules:
  - host: website1.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mysvc-1
            port:
              number: 80