apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  labels:
    app: Ingress
    environment: demo
    authorship: sunil
spec:
  rules:
  - host: website1.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mysvc-np-1
            port:
              number: 80
  - host: website2.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mysvc-np-2
            port:
              number: 80
  - host: website3.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mysvc-np-3
            port:
              number: 80